name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: make

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: circle_test
          POSTGRES_USER: circleci-demo-go
          POSTGRES_PASSWORD: dbpassword
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Test
      run: go test -v ./...
      env:
        CONTACTS_DB_URL: "postgres://circleci-demo-go:dbpassword@localhost:5432/circle_test?sslmode=disable"
        CONTACTS_DB_MIGRATIONS: ${{github.workspace}}/db/migrations
